var w,h;function spherevolMain(){this.version='0.80';w=360;h=350;var id="circ";var s="";s+='<div style="position:relative; width:'+w+'px; height:'+h+'px; border: none; margin:auto; display:block;">';s+='<img id="sphere" src="../geometry/images/sphere-vol.svg" style="z-index:1; position: absolute; top: 2px; left: 2px;" />';s+='<input type="text" id="rad" style="font-size: 17px; position:absolute; left:165px; top:129px; width:122px; z-index:2; color: #19aeff; background-color: #f0f8ff; text-align:center; border-radius: 10px; " value="" onKeyUp="chgRad(this.value)" />';s+='<input type="text" id="dia" style="font-size: 17px; position:absolute; left:165px; top:172px; width:122px; z-index:2; color: #4e9a06; background-color: #f0f8ff; text-align:center; border-radius: 10px; " value="" onKeyUp="chgDia(this.value)" />';s+='<input type="text" id="area" style="font-size: 17px; position:absolute; left:150px; top:330px; width:140px; z-index:2; color: #3465a4; background-color: #f0f8ff; text-align:center; border-radius: 10px; " value="" onKeyUp="chgArea(this.value)" />';s+='<input type="text" id="vol" style="font-size: 17px; position:absolute; left:150px; top:365px; width:140px; z-index:2; color: #000000; background-color: #f0f8ff; text-align:center; border-radius: 10px; " value="" onKeyUp="chgVol(this.value)" />';s+='<div id="copyrt" style="font: 10px Arial; color: blue; position:absolute; bottom:3px; right:8px;">&copy; 2016 MathsIsFun.com  v'+this.version+'</div>';s+='</div>';document.write(s);document.getElementById("rad").value=10;chgRad(10);}
function chgRad(v){var radi=getNumPart(v);var unit=getUnitPart(v);document.getElementById("dia").value=fmtNum(radi*2,unit);document.getElementById("area").value=fmtNum(4*Math.PI*radi*radi,unit,2);document.getElementById("vol").value=fmtNum((4/3)*Math.PI*radi*radi*radi,unit,3);}
function chgDia(v){var diam=getNumPart(v);var unit=getUnitPart(v);var radi=diam/2;document.getElementById("rad").value=fmtNum(radi,unit);document.getElementById("area").value=fmtNum(4*Math.PI*radi*radi,unit,2);document.getElementById("vol").value=fmtNum((4/3)*Math.PI*radi*radi*radi,unit,3);}
function chgArea(v){var area=getNumPart(v);var unit=getUnitPart(v);var radi=Math.sqrt(area/(4*Math.PI));document.getElementById("rad").value=fmtNum(radi,unit);document.getElementById("dia").value=fmtNum(radi*2,unit);document.getElementById("vol").value=fmtNum((4/3)*Math.PI*radi*radi*radi,unit,3);}
function chgVol(v){var vol=getNumPart(v);var unit=getUnitPart(v);var radi=Math.pow(vol/((4/3)*Math.PI),1/3);document.getElementById("rad").value=fmtNum(radi,unit);document.getElementById("dia").value=fmtNum(radi*2,unit);document.getElementById("area").value=fmtNum(4*Math.PI*radi*radi,unit,2);}
function getNumPart(text){return splitNum(text,true);}
function getUnitPart(text){return splitNum(text,false);}
function splitNum(text,wantNumQ){var s=""
var splitCol=0;var isAllNumQ=true;for(var i=0;i<text.length;i++){var isNumQ=false;var charCode=text.charCodeAt(i);if(charCode==45&&i==0)
isNumQ=true;if(charCode==46)
isNumQ=true;if(charCode>=48&&charCode<=57)
isNumQ=true;if(!isNumQ){isAllNumQ=false;splitCol=i;break;}}
if(wantNumQ){if(isAllNumQ){return text;}else{return text.substr(0,splitCol);}}else{if(isAllNumQ){return "";}else{return text.substr(splitCol).trim();}}}
function fmtNum(val,unit,exp){exp=typeof exp!=='undefined'?exp:1;var s="";if(unit.length>0){if(unit.charAt(unit.length-1)=="²"||unit.charAt(unit.length-1)=="³"){unit=unit.substr(0,unit.length-1);}
s=fmt(val,7)+" "+unit;if(exp==2)s+="²";if(exp==3)s+="³";}else{s=fmt(val,10);}
return s;}
function fmt(val,len){return val.toPrecision(len);}